# The overall format is standard TOML format, v0.5.0.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[39,)" #mandatory
issueTrackerURL="https://github.com/Sinhika/ClassicalAlchemy/issues"
license="LGPL 3"

[[mods]]
modId="classicalalchemy"
version="${file.jarVersion}"
displayName="akkamaddi's Classical Alchemy"
updateJSONURL="https://raw.githubusercontent.com/Sinhika/ClassicalAlchemy/1.18/update.json"
displayURL="http://minecraft.curseforge.com/projects/akkamaddis-classical-alchemy"
credits="Thanks to akkamaddi for creating the original mod (with help from AleXndrTheGr8st) and to Sinhika for porting and maintaining it."
authors="akkamaddi, Sinhika"
description='''Addition of Cuprum, Stannum, Pyropus Bronze, Pulchrum Bronze, and Tomb Bronze (with Arsenic and Lace). Fusion Furnace and Simple Ores add-on.
'''

[[dependencies.classicalalchemy]]
    modId="forge"
    mandatory=true
    versionRange="[39.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.classicalalchemy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.18.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.classicalalchemy]]
    modId="simplecorelib"
    mandatory=true
    versionRange="[1.18.1-4.0.1.0, 1.18.2)"
    ordering="NONE"
    side="BOTH"    

[[dependencies.classicalalchemy]]
    modId="simpleores"
    mandatory=false
    versionRange="[1.18.1-4.0.0.3, 1.18.2)"
    ordering="BEFORE"
    side="BOTH"    

[[dependencies.classicalalchemy]]
    modId="fusion"
    mandatory=true
    versionRange="[1.18.1-4.0.1.0, 1.18.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.classicalalchemy]]
        modId="arsenic"
        mandatory=false
        versionRange="[ 1.18.1-4.0.0.2,1.18.2)"
        ordering="BEFORE"
        side="BOTH"
    
#[[dependencies.classicalalchemy]]
#        modId="silents_mechanisms"
#        mandatory=false
#        versionRange="[0.8.9,)"
#        ordering="BEFORE"
#        side="BOTH"
#        
#[[dependencies.classicalalchemy]]
#        modId="silentgear"
#        mandatory=false
#        versionRange="[2.6.5,)"
#        ordering="BEFORE"
#        side="BOTH"
#        

