# The overall format is standard TOML format, v0.5.0.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="${loader_version_range}" #mandatory
issueTrackerURL="https://github.com/Sinhika/ClassicalAlchemy/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/Sinhika/ClassicalAlchemy/1.20/update.json"
displayURL="http://minecraft.curseforge.com/projects/akkamaddis-classical-alchemy"
credits="Thanks to akkamaddi for creating the original mod (with help from AleXndrTheGr8st) and to Sinhika for porting and maintaining it."
authors="${mod_authors}"
description='''Addition of Cuprum, Stannum, Pyropus Bronze, Pulchrum Bronze, and Tomb Bronze (with Arsenic and Lace). Fusion Furnace and Simple Ores add-on.
'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="simplecorelib"
    mandatory=true
    versionRange="${simplecore_range}"
    ordering="NONE"
    side="BOTH"    

[[dependencies.${mod_id}]]
    modId="simpleores"
    mandatory=false
    versionRange="${simpleores_range}"
    ordering="BEFORE"
    side="BOTH"    

[[dependencies.${mod_id}]]
    modId="fusion"
    mandatory=true
    versionRange="${fusion_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
        modId="arsenic"
        mandatory=false
        versionRange="${arsenic_range}"
        ordering="BEFORE"
        side="BOTH"

[[dependencies.${mod_id}]]
    modId="bucketlib"
    mandatory=false
    versionRange="${buckletlib_range}"
    ordering="BEFORE"
    side="BOTH"
         
